apiVersion: batch/v1
kind: Job
metadata:
  name: wnste-arch-job
spec:
  template:
    spec:
      containers:
      - name: wnste-arch-job
        image: yash5090/wnste-arch:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
