apiVersion: apps/v1
kind: Deployment
metadata:
  name: wnste-arch-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: wnste-arch
  template:
    metadata:
      labels:
        app: wnste-arch
    spec:
      containers:
        - name: wnste-arch
          image: yash5090/wnste-arch:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
